// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyKAUN3rgkh0_GZBciPCTRwSTaFaOR8Fw',
    appId: '1:586582966668:web:5abd60ddc78004151516a9',
    messagingSenderId: '586582966668',
    projectId: 'jrod-scrum-poker',
    authDomain: 'jrod-scrum-poker.firebaseapp.com',
    storageBucket: 'jrod-scrum-poker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEW4qq7uP12fTY13Jf6I5egUiqQBGaDR8',
    appId: '1:586582966668:android:516fff523d0241661516a9',
    messagingSenderId: '586582966668',
    projectId: 'jrod-scrum-poker',
    storageBucket: 'jrod-scrum-poker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf4unfR6WDbhCY7Z8pnsPIxa2vJKN9lME',
    appId: '1:586582966668:ios:d665c4f642f3507d1516a9',
    messagingSenderId: '586582966668',
    projectId: 'jrod-scrum-poker',
    storageBucket: 'jrod-scrum-poker.firebasestorage.app',
    iosBundleId: 'com.example.scrumPocker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf4unfR6WDbhCY7Z8pnsPIxa2vJKN9lME',
    appId: '1:586582966668:ios:d665c4f642f3507d1516a9',
    messagingSenderId: '586582966668',
    projectId: 'jrod-scrum-poker',
    storageBucket: 'jrod-scrum-poker.firebasestorage.app',
    iosBundleId: 'com.example.scrumPocker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyKAUN3rgkh0_GZBciPCTRwSTaFaOR8Fw',
    appId: '1:586582966668:web:58a30179abd9f85c1516a9',
    messagingSenderId: '586582966668',
    projectId: 'jrod-scrum-poker',
    authDomain: 'jrod-scrum-poker.firebaseapp.com',
    storageBucket: 'jrod-scrum-poker.firebasestorage.app',
  );
}
